# Generated by cpp11: do not edit by hand

cpp_bbox_handler_new <- function() {
  .Call(`_wk_programming_cpp_bbox_handler_new`)
}

cpp_handle_xy <- function(input, handler_xptr) {
  .Call(`_wk_programming_cpp_handle_xy`, input, handler_xptr)
}
